// GENERATED by tools/render-store.mjs from products.json. Do not edit.
// The checkout functions price every order from this, never from the browser.
export const catalog = {
  "compost-monthly": {
    "id": "compost-monthly",
    "name": "Compost Pick-up",
    "price": 2000,
    "interval": "month",
    "active": true,
    "paypalPlanId": null,
    "paypalSandboxPlanId": null,
    "ship": false,
    "shipOz": null,
    "waiver": null
  },
  "recycle-monthly": {
    "id": "recycle-monthly",
    "name": "Recycling Pick-Up",
    "price": 1500,
    "interval": "month",
    "active": true,
    "paypalPlanId": null,
    "paypalSandboxPlanId": null,
    "ship": false,
    "shipOz": null,
    "waiver": null
  },
  "soccer-player-fall": {
    "id": "soccer-player-fall",
    "name": "Player Registration: 7v7 Adult Soccer League (Fall Season)",
    "price": 2500,
    "interval": null,
    "active": true,
    "paypalPlanId": null,
    "paypalSandboxPlanId": null,
    "ship": false,
    "shipOz": null,
    "waiver": {
      "version": "2026-09"
    }
  },
  "soccer-team-fall": {
    "id": "soccer-team-fall",
    "name": "Team Registration: 7v7 Adult Soccer",
    "price": 25000,
    "interval": null,
    "active": true,
    "paypalPlanId": null,
    "paypalSandboxPlanId": null,
    "ship": false,
    "shipOz": null,
    "waiver": {
      "version": "2026-09"
    }
  }
};
