// The SeedsNow preview on the Store's Green Swaps view (owner, 2026-10-10:
// "a product preview shelf so users can see on our own website what type of
// products SeedsNow has ... include the SeedsNow prices ... ensure all of those
// products also have our affiliate link").
//
//   node tools/seedsnow-shelf.mjs        read SeedsNow's public catalogue
//                                        (its Shopify products.json), pick the
//                                        shelves below, rewrite store.html
//                                        between the SEEDSNOW markers
//
// Run it again now and then: prices and stock are SeedsNow's and change.
// Every link carries our Refersion affiliate code (affiliates.json).
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const AFF = 'rfsn=9367513.1d5a377&utm_source=refersion&utm_medium=affiliate&utm_campaign=9367513.1d5a377';
const link = (path) => `https://www.seedsnow.com${path}?${AFF}`;

// [shelf title, SeedsNow product types, how many]
const SHELVES = [
  ['Variety packs and seed banks', ['*Variety Packs', '*Seed Banks'], 8],
  ['Vegetables', ['Tomato (Indeterminate)', 'Tomato (Determinate)', 'Pepper (Sweet)', 'Pepper (Hot)', 'Lettuce', 'Cucumber', 'Carrot', 'Bean, Bush', 'Squash (Summer)', 'Kale', 'Radish', 'Spinach', 'Watermelon', 'Okra'], 10],
  ['Herbs', ['Basil', 'Cilantro (Coriander)', 'Parsley', 'Chamomile', 'Lavender', 'Mint', 'Oregano', 'Thyme', 'Dill', 'Rosemary', 'Chive', 'Sage'], 10],
  ['Flowers and pollinators', ['Wildflower Mix', 'Sunflower', 'Zinnia', 'Milkweed', 'Coneflower', 'Marigold', 'Nasturtium', 'Cosmos', 'Lupine', 'Bee Balm'], 10],
  ['Sprouts and microgreens', ['Sprouts & Microgreens'], 8],
  ['Garlic, onions and shallots', ['Garlic', 'Onion (Sets & Transplants)', 'Shallot'], 6],
  ['Seed starting and saving', ['Seed Starting Soil Pods', 'Supplies & More', 'Mylar Seed Saver Bags', 'Seed Storage Vault'], 6],
];
// Always first on the flowers shelf: the mix made for our own region.
const PIN = ['wildflowers-texas-oklahoma-seed-mix'];

async function catalogue() {
  const all = [];
  for (let page = 1; page <= 10; page++) {
    const res = await fetch(`https://www.seedsnow.com/products.json?limit=250&page=${page}`, { headers: { 'User-Agent': 'Mozilla/5.0 (lavishleaf.org affiliate shelf)' } });
    if (!res.ok) throw new Error(`SeedsNow said ${res.status} on page ${page}`);
    const { products } = await res.json();
    if (!products.length) break;
    all.push(...products);
  }
  return all;
}

const esc = (t) => String(t).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;');
// Their titles carry stars, emoji and "seeds"; a card reads better without.
const clean = (t) => t.replace(/\*NEW\*\s*/i, '').replace(/\*/g, '').replace(/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}\u{FE0F}]/gu, '').replace(/\s+seeds$/i, '').replace(/\s+/g, ' ').trim();
const small = (src) => src + (src.includes('?') ? '&' : '?') + 'width=360';

function card(p) {
  const live = p.variants.filter((v) => v.available);
  const prices = live.map((v) => Number(v.price));
  const min = Math.min(...prices);
  const price = (new Set(prices).size > 1 ? 'From $' : '$') + min.toFixed(2);
  const name = clean(p.title);
  return [
    `  <article class="sp-card gs-sn-card">`,
    `    <a class="sp-media" href="${esc(link('/products/' + p.handle))}" target="_blank" rel="sponsored noopener" data-affiliate="SeedsNow" data-sn="${esc(p.handle)}" tabindex="-1" aria-hidden="true"><img src="${esc(small(p.images[0].src))}" alt="${esc(name)}" loading="lazy"></a>`,
    `    <h3 class="sp-name">${esc(name)}</h3>`,
    `    <div class="sp-foot">`,
    `      <span class="sp-price">${price}</span>`,
    `      <a class="btn btn-sm" href="${esc(link('/products/' + p.handle))}" target="_blank" rel="sponsored noopener" data-affiliate="SeedsNow" data-sn="${esc(p.handle)}">View at SeedsNow</a>`,
    `    </div>`,
    `  </article>`,
  ].join('\n');
}

const all = await catalogue();
const ok = (p) => p.variants.some((v) => v.available) && p.images[0];
const shelves = SHELVES.map(([title, types, n]) => {
  const pools = types.map((t) => all.filter((p) => p.product_type === t && ok(p)));
  const items = [];
  for (const h of PIN) { const p = all.find((x) => x.handle === h && ok(x)); if (p && types.includes(p.product_type)) items.push(p); }
  for (let k = 0; items.length < n && pools.some((pl) => pl.length > k); k++) {
    for (const pl of pools) if (pl[k] && items.length < n && !items.includes(pl[k])) items.push(pl[k]);
  }
  return { title, items };
}).filter((s) => s.items.length);

const today = new Date().toISOString().slice(0, 10);
const html = [
  `<!-- SEEDSNOW:START (generated by tools/seedsnow-shelf.mjs on ${today}; do not edit by hand) -->`,
  ...shelves.map((s) => [
    `<section class="shelf gs-sn-shelf">`,
    `  <div class="shelf-head"><h2>${esc(s.title)}</h2><a class="shelf-all" href="${esc(link('/'))}" target="_blank" rel="sponsored noopener" data-affiliate="SeedsNow">More at SeedsNow</a></div>`,
    `  <div class="shelf-row">`,
    s.items.map(card).join('\n'),
    `  </div>`,
    `</section>`,
  ].join('\n')),
  `<p class="gs-sn-note">Prices and stock are SeedsNow's, read on ${today}; SeedsNow's own page has today's price.</p>`,
  `<!-- SEEDSNOW:END -->`,
].join('\n');

const file = join(ROOT, 'store.html');
let page = readFileSync(file, 'utf8');
const nl = page.includes('\r\n') ? '\r\n' : '\n';
const re = /<!-- SEEDSNOW:START[\s\S]*?<!-- SEEDSNOW:END -->/;
if (!re.test(page)) throw new Error('store.html has no SEEDSNOW markers');
page = page.replace(re, () => html.replace(/\n/g, nl));
writeFileSync(file, page);
console.log(`SeedsNow: ${shelves.map((s) => `${s.title} ${s.items.length}`).join(', ')}.`);
